### PR TITLE
Doc: fix configuration key in sandbox-vs-live.md file

### PR DESCRIPTION
**Pull request by toofff**

### CODE REVIEW

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
The build is not passing due to problems on Sylius, I will merge it as soon as these problems are solved 🖖

**Comment by toofff** [comment]
I saw a problem in the configuration, do not merge for the moment please

**Comment by Zales0123** [comment]
Hello, @toofff 🖖 I've rebased your PR and I think it's still a valid fix - according to our [Configuration file](https://github.com/Sylius/PayPalPlugin/blob/master/src/DependencyInjection/Configuration.php#L14), it should indeed be `sylius_pay_pal_plugin`

**Comment by Zales0123** [comment]
Thank you, @toofff! :1st_place_medal:

**Pull request merged**
