### PR TITLE
Remove conflict in composer.json

### LINKED ISSUE #173: Conflict with symplify/package-builder
This packages `composer.json` marks `symplify/package-builder` versions "^8.3.24" as conflicting.

With sylius 1.8.5 I get `symplify/package-builder` version 8.3.48

Sylius/CodingStandard requires `"symplify/easy-coding-standard": "^7.3 || ^8.1"` ([see here](https://github.com/SyliusLabs/CodingStandard/blob/master/composer.json))

I can't downgrade `symplify/easy-coding-standard` to 7.3 because `sylius/grid-bundle v1.7.5` conflicts with `symplify/smart-file-system v7.3.18`

Here is what happens when I `composer require sylius/paypal-plugin`:

```
Using version ^1.1 for sylius/paypal-plugin
./composer.json has been updated
Running composer update sylius/paypal-plugin
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires sylius/paypal-plugin ^1.1 -> satisfiable by sylius/paypal-plugin[v1.1.0].
    - symplify/easy-coding-standard 8.3.48 requires symplify/package-builder ^8.3.48 -> satisfiable by symplify/package-builder[8.3.48].
    - sylius-labs/coding-standard v3.2.1 requires symplify/easy-coding-standard ^7.3 || ^8.1 -> satisfiable by symplify/easy-coding-standard[8.3.48].
    - symplify/package-builder 8.3.48 conflicts with sylius/paypal-plugin v1.1.0.
    - sylius-labs/coding-standard is locked to version v3.2.1 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I don't see how I can work around this.

So what is the reason for the conflict being declared in PayPalPlugin's composer.json in the first place?

### PR DESCRIPTION
**Pull request by armellarcier**
symplify/package-builder is no more conflicting with sylius

closes #173

### CODE REVIEW

**Comment by armellarcier** [comment]
@Zales0123 composer analysis IS broken. Insights ?

**Comment by Zales0123** [comment]
As far as I see, the problem is deeper :/ It's the same issue as here: https://github.com/Sylius/Sylius/issues/12017. Maybe we should fix it on the level of `sylius-labs/coding-standard`

**Review by Zales0123 — APPROVED** [review]
I believe it's indeed not needed anymore 🖖

**Comment by Zales0123** [comment]
Thank you, Armel! :tada:

**Pull request merged**
